name = "TopologicalInterfaces"
uuid = "0fa5e18a-6159-4dfd-8535-a2ced8d81a48"
authors = ["Ivan Spirandelli <spirandelli@uni-potsdam.de>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"