name = "TopologicalInterfaces"
uuid = "0fa5e18a-6159-4dfd-8535-a2ced8d81a48"
authors = ["Ivan Spirandelli <spirandelli@uni-potsdam.de>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
